const SOURCES=[['WEB','Serper / Exa'],['OPEN','HN / GitHub'],['FORUM','BHW / BBHF'],['OSINT','Domain / Identity'],['SOCIAL','Reddit / X / XHS'],['MARKET','Polymarket']];
const ROUTES={balanced:[['QUERY PLAN','拆分实体、观点与证据需求'],['OPEN WEB','Serper + Exa 建立候选集'],['DEEP FORUM','Obscura 公开采集 + Chrome 登录态深采'],['OSINT VERIFY','公开主体信息交叉验证'],['NORMALIZE','转 Markdown、去重、置信度排序']],forums:[['QUERY PLAN','识别圈内术语与同义表达'],['FORUM DISCOVERY','定位站点、板块与主题页'],['LIGHT CRAWL','Obscura 抓公开主题、分页与链接'],['SESSION CRAWL','Chrome CDP 处理登录、验证码与人工接管'],['NORMALIZE','证据对象与原始链接']],osint:[['ENTITY MAP','提取域名、组织、账号与人员'],['PUBLIC RECORDS','DNS、WHOIS、证书与历史快照'],['IDENTITY PIVOT','公开用户名和邮件线索关联'],['CROSS CHECK','时间线与多源一致性校验'],['NORMALIZE','证据等级与未知项']],fast:[['WEB SEARCH','Serper 秒级召回'],['OPEN SOURCES','HN、GitHub 与公开社区'],['SNIPPET RANK','按相关性和新鲜度排序'],['RETURN','保留来源与抓取时间']]};
const DEMO=[
 {source:'FORUM / BHW',age:'3d',title:'“不要先做流量，先潜伏在用户已经抱怨的工作流里”',text:'多名实操者把早期增长归因于在小型专业社区中解决具体失败案例，而不是发布泛化产品帖。评论树里反复出现 onboarding 和结果可信度问题。',confidence:'HIGH',method:'OBSCURA / CDP',type:'非标论坛'},
 {source:'HACKER NEWS',age:'8h',title:'Show HN 的第一批用户，更像审稿人而不是客户',text:'高质量讨论集中在技术取舍、数据来源和可复现性。适合验证产品可信度，不适合把点赞数直接当购买意图。',confidence:'HIGH',method:'ALGOLIA API',type:'开放社区'},
 {source:'GITHUB ISSUES',age:'1d',title:'用户会在 issue 里写出搜索页永远不会出现的需求句子',text:'“支持导出证据”“保留原始链接”“能够重跑同一查询”是多个研究工具仓库里的重复需求，可直接转为产品路线和落地页语言。',confidence:'HIGH',method:'REST SEARCH',type:'产品证据'},
 {source:'OSINT / WEB',age:'LIVE',title:'竞品实体图：产品站、文档站、创始人账号与社区足迹并不一致',text:'公开 DNS、历史页面和账号命名显示，部分“新产品”其实来自既有团队的第二品牌。这个信息会改变竞品年龄与增长速度的判断。',confidence:'MEDIUM',method:'PUBLIC RECORDS',type:'OSINT 补证'},
 {source:'REDDIT',age:'5d',title:'购买意图藏在“我试过三个工具但都失败了”的叙述里',text:'相比泛关键词，带有替代、迁移、成本失控和结果不可解释的帖子，更适合作为产品切入点与挖词种子。',confidence:'MEDIUM',method:'APIFY ACTOR',type:'社媒社区'},
 {source:'POLYMARKET',age:'LIVE',title:'市场信号只回答“人们押什么”，不回答“为什么”',text:'预测市场适合校准事件概率与时间窗口；必须与论坛理由、新闻时间线和主体公开记录组合，不能独立生成结论。',confidence:'MEDIUM',method:'PUBLIC SEARCH',type:'市场信号'}
];
let currentMode='balanced';
const sourceStrip=document.getElementById('sourceStrip');
SOURCES.forEach(([kind,label],i)=>{const b=document.createElement('button');b.type='button';b.className=`source-chip ${i===0?'active ':''}${['FORUM','OSINT'].includes(kind)?'deep':''}`;b.innerHTML=`<i></i><strong>${kind}</strong> ${label}`;b.onclick=()=>b.classList.toggle('active');sourceStrip.appendChild(b)});
function drawRoute(){document.getElementById('routeTrace').innerHTML=ROUTES[currentMode].map(([a,b])=>`<li><strong>${a}</strong>${b}</li>`).join('')}
function drawResults(items,live=false){const root=document.getElementById('results');root.innerHTML=items.map((x,i)=>`<article class="result" style="animation-delay:${i*55}ms"><div class="result-source">${x.source}<small>${x.age||'NOW'}</small></div><div><h3><a href="${x.url||'#'}">${x.title}</a></h3><p>${x.text||x.snippet||''}</p><div class="evidence-meta"><span>${x.type||'SIGNAL'}</span><span>${x.method||x.backend||'ROUTED'}</span><span class="confidence-${String(x.confidence||'medium').toLowerCase()}">${x.confidence||'MEDIUM'} CONFIDENCE</span></div></div></article>`).join('');document.getElementById('resultCount').textContent=items.length;document.getElementById('resultMode').textContent=live?'LIVE EVIDENCE':'DEMO EVIDENCE'}
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentMode=b.dataset.mode;drawRoute()});
document.getElementById('searchForm').addEventListener('submit',async e=>{e.preventDefault();const query=document.getElementById('query').value.trim();if(!query)return;const progress=document.getElementById('progress');const results=document.getElementById('results');progress.hidden=false;results.style.opacity='.35';document.getElementById('resultTitle').textContent=`“${query}” 的证据流`;try{const r=await fetch('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query,mode:currentMode})});if(!r.ok)throw new Error('demo');const data=await r.json();drawResults(data.results||data,true)}catch{await new Promise(r=>setTimeout(r,850));drawResults(DEMO.map(x=>({...x,title:x.title.replace('用户',query.length<18?query:'用户')})),false)}finally{progress.hidden=true;results.style.opacity='1'}});
document.getElementById('themeToggle').onclick=()=>{const h=document.documentElement;const dark=h.dataset.theme==='dark';h.dataset.theme=dark?'light':'dark';document.getElementById('themeToggle').textContent=dark?'DARK':'LIGHT'};
drawRoute();drawResults(DEMO);
